# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordAT
                                 A QGIS plugin
 adds points' coordinates to attribute table, according to the chosen CRS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-21
        copyright            : (C) 2020 by Romário Moraes Carvalho Neto
        email                : romariocarvalho@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordAT class from file CoordAT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coord_attributable import CoordAT
    return CoordAT(iface)
